
server.port=8081

spring.datasource.url=jdbc:postgresql://192.168.124.8:8432/postgres
spring.datasource.username=vxpt
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=5MB  
spring.servlet.multipart.max-request-size=10MB 



